deamon:
  pid_file: ./financial_app.pid
log:
  log_level: debug
  log_file: log/financial_app.log
  log_format: text # json -> to output in json format
config_files:
  queries_files: ./config/queries.yaml
database:
  host: 192.168.0.140
  port: 5432
  admin_user: wolfgres_user
  admin_pass: password
  test_user: wolfgres_user
  test_pass: postgres
  database_name: wolfgres_db
random_data:
  regions: 5
  warehouses: 10
  districts: 5
  products: 10000
  employees: 1000
  customers: 500 # 1 a 10 contacts per customer
test:
  type: stress      # load -> only inserts or stress -> the stress test make inserts updates deletes and selects
  target_type: size # or orders 
  target_orders: 10000
  target_size: 10240 # Target size in MB
  orders_by_loop: 30 # Must be minor to 50
  updates_by_loop: 10 
  deletes_by_loop: 10
  min_workers: 5
  max_workers: 20
  time_sleep: 3 # seconds
  max_conn_percent: 20 # percent of connections available to keep
  max_conn_sleep: 30 # seconds
target:
  size: 0 #The target stress test in MB size, 0 is desactivated
  concurrent_users:
    min: 10
    max: 20
  concurrent_time:
    min: 60
    max: 120