deamon:
  pid_file: ./financial_app.pid
log:
  log_level: debug
  log_file: bin/log/financial_app.log
  log_format: text # json -> to output in json format
database:
  host: localhost
  port: 5432
  admin_user: postgres
  admin_pass: postgres
  database_name: wolfgres_db
