global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: postgres-exporter-primary
    static_configs:
      - targets: ["postgres-exporter-primary:9187"]

  - job_name: postgres-exporter-secondary
    static_configs:
      - targets: ["postgres-exporter-secondary:9187"]
